CREATE TABLE IF NOT EXISTS locations (
    id SERIAL PRIMARY KEY,
    phone VARCHAR(32) NOT NULL,
    latitude DECIMAL(9,6) NOT NULL,
    longitude DECIMAL(9,6) NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
